/* file generated by oo2c -- do not edit */
#include "__oo2c.h"
#include "__libc.h"
/* file generated by oo2c -- do not edit */
#include "Terminal.h"
#include <conio.h>
/* local definitions */

/* function prototypes */

/* module and type descriptors */
static const struct {
  int length;
  void* pad;
  const void* list[3];
} _p0 = {3, NULL, {
  (const void*)&Terminal__Get,
  (const void*)&Terminal__Put,
  (const void*)&Terminal__PutInt,
}};
static const struct {
  int length;
  void* pad;
  const void* list[1];
} _p1 = {0, NULL, {NULL
}};
static const struct {
  int length;
  void* pad;
  const char name[9];
} _n0 = {9, NULL, {"Terminal"}};
static struct _MD Terminal_md = {
  NULL, 
  &Kernel__ModuleDesc_td.td, 
  {
    NULL, 
    (const unsigned char*)_n0.name, 
    -1, 
    NULL,
    _p0.list,
    _p1.list,
    1123346759
  }
};

/* local strings */


static _ModId _mid;

void Terminal__Put(unsigned char c) {
cprintf ("%c",c);
}

void Terminal__PutInt(int c) {
cprintf ("%i",c);
}

void Terminal__Get(unsigned char *c) {
//scanf("%c",c);
*c = cgetc();
//cputc(c);
}

void Terminal_init(void) {
  _mid = _register_module(&Terminal_md.md, NULL);
}

